"""Human-readable per-project DIGEST.md, regenerated from the index."""
import os, json, datetime
from .config import MEMORY_DIR


def _dur(s):
    h, m = divmod(int(s or 0) // 60, 60)
    return f"{h}h{m:02d}m" if h else f"{m}m"


def _n(x):
    x = x or 0
    if x >= 1_000_000_000: return f"{x/1e9:.1f}B"
    if x >= 1_000_000: return f"{x/1e6:.1f}M"
    if x >= 1_000:     return f"{x/1e3:.1f}k"
    return str(x)


def write_all(con, project=None):
    q = "SELECT DISTINCT project_id FROM episodes"
    args = []
    if project:
        q += " WHERE project_id LIKE ?"; args.append(f"%{project}%")
    out = []
    for row in con.execute(q, args).fetchall():
        out.append(write_one(con, row["project_id"]))
    idx = write_index(con)
    out.append(idx)
    return out


def write_one(con, pid):
    lbl = con.execute("SELECT name,paths FROM projects WHERE id=?", (pid,)).fetchone()
    name = lbl["name"] if lbl else pid
    paths = json.loads(lbl["paths"]) if lbl else []
    eps = con.execute("SELECT * FROM episodes WHERE project_id=? ORDER BY started DESC", (pid,)).fetchall()
    agg = con.execute("SELECT COUNT(*) n,SUM(out_tokens) o,SUM(n_prompts) p,SUM(duration_s) d,"
                      "SUM(compactions) k,COUNT(DISTINCT substr(started,1,10)) days "
                      "FROM episodes WHERE project_id=?", (pid,)).fetchone()
    runs = con.execute("SELECT COUNT(*) n FROM agent_runs WHERE project_id=?", (pid,)).fetchone()

    d = MEMORY_DIR / "projects" / pid
    d.mkdir(parents=True, exist_ok=True)
    L = []
    L.append(f"# {name}\n")
    L.append(f"*Generated by Chronicle {datetime.date.today().isoformat()} — do not edit; "
             f"put durable notes in `decisions.md` beside this file.*\n")
    L.append(f"- **{agg['n']} episodes** over {agg['days']} active days · "
             f"{agg['p']} prompts · {_dur(agg['d'])} elapsed · {_n(agg['o'])} output tokens")
    L.append(f"- **{runs['n']} agent runs** · {agg['k']} compactions")
    if paths:
        L.append("- Paths: " + ", ".join(f"`{p}`" for p in paths))
    L.append("\n## Timeline\n")
    for e in eps:
        files = json.loads(e["files_touched"] or "[]")
        bits = [f"{e['n_prompts']}p", _dur(e["duration_s"])]
        if files: bits.append(f"{len(files)} files")
        if e["n_agents"]: bits.append(f"{e['n_agents']} agents")
        L.append(f"### {e['started'][:10]} — {e['title']}")
        L.append(f"`#{e['id']}` · {' · '.join(bits)}")
        if files:
            L.append("<details><summary>files</summary>\n")
            for f in files[:40]:
                L.append(f"- `{f}`")
            L.append("\n</details>")
        L.append("")
    p = d / "DIGEST.md"
    p.write_text("\n".join(L))
    dec = d / "decisions.md"
    if not dec.exists():
        dec.write_text(f"# {name} — decisions & context\n\n"
                       "Hand-written. Chronicle never touches this file.\n"
                       "Record the *why*: choices made, approaches abandoned, current blockers.\n")
    return str(p)


def write_index(con):
    rows = con.execute("""SELECT project_id p, COUNT(*) n, MAX(ended) last,
                          COUNT(DISTINCT substr(started,1,10)) d, SUM(out_tokens) o
                          FROM episodes GROUP BY project_id ORDER BY last DESC""").fetchall()
    L = ["# Memory index\n",
         f"*Generated by Chronicle {datetime.date.today().isoformat()}. "
         f"Ask questions here — see `.claude/skills/chronicle/SKILL.md`.*\n",
         "| Project | Episodes | Active days | Output | Last touched |",
         "|---|--:|--:|--:|---|"]
    for r in rows:
        lbl = con.execute("SELECT name FROM projects WHERE id=?", (r["p"],)).fetchone()
        name = lbl["name"] if lbl else r["p"]
        L.append(f"| [{name}](projects/{r['p']}/DIGEST.md) | {r['n']} | {r['d']} | "
                 f"{_n(r['o'])} | {r['last'][:10]} |")
    p = MEMORY_DIR / "MEMORY.md"
    p.write_text("\n".join(L) + "\n")
    return str(p)
