"""Install Chronicle's hooks into Claude Code settings, plus a background indexer.

Merges — never clobbers. Existing hooks from other tools are preserved, and every
write is backed up first.
"""
import os, sys, json, shutil, subprocess, datetime, pathlib
from .config import MEMORY_DIR, ROOT, INSTALL_DIR

SETTINGS = pathlib.Path.home() / ".claude" / "settings.json"
SKILL_SRC = INSTALL_DIR / "skill" / "SKILL.md.tmpl"
SKILL_DST = pathlib.Path.home() / ".claude" / "skills" / "chronicle" / "SKILL.md"
PLIST = pathlib.Path.home() / "Library" / "LaunchAgents" / "ai.chronicle.index.plist"
LAUNCHER = MEMORY_DIR / "chronicle-hook"
MARK = "chronicle.cli hook"          # how we recognise our own entries

EVENTS = {
    "PreCompact":       ("*",       "precompact",       600),
    "SessionStart":     ("*",       "sessionstart",      20),
    "SessionEnd":       ("*",       "sessionend",         5),
    "UserPromptSubmit": ("",        "userpromptsubmit",  10),
}


def _install_skill():
    """Render the skill into user scope so it answers from any project, not just this folder."""
    if not SKILL_SRC.exists():
        return False
    SKILL_DST.parent.mkdir(parents=True, exist_ok=True)
    SKILL_DST.write_text(SKILL_SRC.read_text().replace("{{CHRONICLE_DIR}}", str(INSTALL_DIR)))
    return True


def _launcher():
    """Delegate to chronicle-cli so the interpreter and PYTHONPATH are resolved in one place.
    Hooks run with the user's project as cwd, so nothing here may depend on the directory."""
    LAUNCHER.write_text(
        "#!/bin/sh\n"
        "# Chronicle hook launcher — generated by `chronicle install`\n"
        f'exec "{INSTALL_DIR}/chronicle-cli" hook "$1"\n')
    LAUNCHER.chmod(0o755)
    return str(LAUNCHER)


BIN_CANDIDATES = ["/opt/homebrew/bin", "/usr/local/bin",
                  str(pathlib.Path.home() / ".local/bin"), str(pathlib.Path.home() / "bin")]


def _link_command():
    """Put `chronicle` on PATH so the docs match what actually works in a terminal."""
    path_dirs = os.environ.get("PATH", "").split(":")
    target = INSTALL_DIR / "chronicle-cli"
    for d in BIN_CANDIDATES:
        p = pathlib.Path(d)
        if not (p.is_dir() and os.access(d, os.W_OK) and d in path_dirs):
            continue
        link = p / "chronicle"
        try:
            if link.is_symlink() or link.exists():
                if link.resolve() == target.resolve():
                    return str(link), True
                return None, False           # something else owns the name; leave it alone
            link.symlink_to(target)
            return str(link), True
        except OSError:
            continue
    return None, False


def _is_ours(h):
    return MARK in json.dumps(h) or str(LAUNCHER) in json.dumps(h)


def _merge(settings, cmd):
    hooks = settings.setdefault("hooks", {})
    added = []
    for event, (matcher, arg, timeout) in EVENTS.items():
        groups = hooks.setdefault(event, [])
        for g in groups:                       # drop any previous Chronicle entry
            g["hooks"] = [h for h in g.get("hooks", []) if not _is_ours(h)]
        groups[:] = [g for g in groups if g.get("hooks")]
        groups.append({
            "matcher": matcher,
            "hooks": [{"type": "command",
                       "command": f"{cmd} {arg}",
                       "timeout": timeout}],
        })
        added.append(event)
    return added


def _strip(settings):
    hooks = settings.get("hooks", {})
    removed = 0
    for event in list(hooks):
        for g in hooks[event]:
            before = len(g.get("hooks", []))
            g["hooks"] = [h for h in g.get("hooks", []) if not _is_ours(h)]
            removed += before - len(g["hooks"])
        hooks[event] = [g for g in hooks[event] if g.get("hooks")]
        if not hooks[event]:
            del hooks[event]
    return removed


PLIST_XML = """<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>Label</key><string>ai.chronicle.index</string>
  <key>ProgramArguments</key>
  <array><string>{py}</string><string>-m</string><string>chronicle.cli</string><string>index</string></array>
  <key>WorkingDirectory</key><string>{cwd}</string>
  <key>EnvironmentVariables</key><dict><key>PYTHONPATH</key><string>{cwd}</string></dict>
  <key>StartInterval</key><integer>1800</integer>
  <key>RunAtLoad</key><true/>
  <key>StandardErrorPath</key><string>{log}</string>
</dict></plist>
"""


MCP_KEY = "chronicle"


def _mcp_entry():
    return {"command": sys.executable, "args": ["-m", "chronicle.mcp"],
            "cwd": str(MEMORY_DIR), "env": {"PYTHONPATH": str(MEMORY_DIR)}}


def install(uninstall=False, mcp=False):
    if uninstall:
        settings = json.loads(SETTINGS.read_text()) if SETTINGS.exists() else {}
        backup = _backup()
        n = _strip(settings)
        SETTINGS.write_text(json.dumps(settings, indent=2) + "\n")
        had_mcp = settings.get("mcpServers", {}).pop(MCP_KEY, None) is not None
        SETTINGS.write_text(json.dumps(settings, indent=2) + "\n")
        for d in BIN_CANDIDATES:
            link = pathlib.Path(d) / "chronicle"
            try:
                if link.is_symlink() and link.resolve() == (INSTALL_DIR / "chronicle-cli").resolve():
                    link.unlink()
            except OSError:
                pass
        subprocess.run(["launchctl", "unload", str(PLIST)], capture_output=True)
        PLIST.unlink(missing_ok=True)
        import shutil as _sh
        if SKILL_DST.exists():
            _sh.rmtree(SKILL_DST.parent, ignore_errors=True)
        print(f"  removed {n} Chronicle hook entr{'y' if n == 1 else 'ies'} and the indexer job"
              + (", and the MCP server" if had_mcp else ""))
        print(f"  backup: {backup}")
        return

    cmd = _launcher()
    skilled = _install_skill()
    linked, ok = _link_command()
    settings = json.loads(SETTINGS.read_text()) if SETTINGS.exists() else {}
    existing = sum(len(g.get("hooks", [])) for gs in settings.get("hooks", {}).values() for g in gs)
    backup = _backup()
    added = _merge(settings, cmd)
    SETTINGS.parent.mkdir(parents=True, exist_ok=True)
    SETTINGS.write_text(json.dumps(settings, indent=2) + "\n")

    PLIST.parent.mkdir(parents=True, exist_ok=True)
    PLIST.write_text(PLIST_XML.format(py=sys.executable, cwd=str(MEMORY_DIR),
                                      log=str(ROOT / "indexer.log")))
    subprocess.run(["launchctl", "unload", str(PLIST)], capture_output=True)
    r = subprocess.run(["launchctl", "load", str(PLIST)], capture_output=True, text=True)

    if mcp:
        settings.setdefault("mcpServers", {})[MCP_KEY] = _mcp_entry()
        SETTINGS.write_text(json.dumps(settings, indent=2) + "\n")

    if skilled:
        print(f"  skill installed: {SKILL_DST}")
    if linked:
        print(f"  command on PATH: {linked} -> chronicle-cli")
    else:
        print(f"  no writable bin dir on PATH — use {INSTALL_DIR}/chronicle-cli, or:")
        print(f"    ln -s {INSTALL_DIR}/chronicle-cli ~/.local/bin/chronicle")
    print(f"  hooks installed: {', '.join(added)}")
    if mcp:
        print(f"  MCP server registered as \"{MCP_KEY}\" (read-only, 9 tools)")
    print(f"  {existing} pre-existing hook(s) from other tools left untouched")
    print(f"  background indexer: every 30 min ({'loaded' if r.returncode == 0 else 'load failed: ' + r.stderr.strip()})")
    print(f"  settings: {SETTINGS}")
    print(f"  backup:   {backup}")
    print("  restart Claude Code for the hooks to take effect")


def _backup():
    if not SETTINGS.exists():
        return "(no previous settings.json)"
    stamp = datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
    dest = ROOT / f"settings.backup-{stamp}.json"
    shutil.copy2(SETTINGS, dest)
    dest.chmod(0o600)          # settings.json may hold API keys
    return str(dest)
