"""Turn the record into something you can send someone."""
import json, datetime, collections
from .ingest import _clean


def parse_since(v):
    if not v:
        return (datetime.date.today() - datetime.timedelta(days=7)).isoformat()
    v = str(v).strip()
    if v.endswith("d") and v[:-1].isdigit():
        return (datetime.date.today() - datetime.timedelta(days=int(v[:-1]))).isoformat()
    if v.endswith("w") and v[:-1].isdigit():
        return (datetime.date.today() - datetime.timedelta(weeks=int(v[:-1]))).isoformat()
    return v[:10]


def build(con, pid=None, since=None, until=None):
    since = parse_since(since)
    until = (until or datetime.date.today().isoformat())[:10]
    q = """SELECT DISTINCT e.* FROM episodes e
           JOIN episode_projects p ON p.episode_id=e.id
           WHERE substr(e.started,1,10) >= ? AND substr(e.started,1,10) <= ?"""
    args = [since, until]
    if pid:
        q += " AND p.project_id = ?"
        args.append(pid)
    q += " ORDER BY e.started"
    eps = con.execute(q, args).fetchall()
    if not eps:
        return None

    name = pid or "All projects"
    if pid:
        r = con.execute("SELECT name FROM projects WHERE id=?", (pid,)).fetchone()
        name = r["name"] if r else pid

    by_day = collections.OrderedDict()
    for e in eps:
        by_day.setdefault(e["started"][:10], []).append(e)

    roots, files = collections.Counter(), set()
    for e in eps:
        for f in json.loads(e["files_touched"] or "[]"):
            files.add(f)
    for e in eps:
        for r in con.execute("SELECT root,n_files FROM episode_projects WHERE episode_id=? "
                             "AND source='files'", (e["id"],)):
            roots[r["root"]] += r["n_files"]

    ids = [e["id"] for e in eps]
    qs = ",".join("?" * len(ids))
    runs = con.execute(f"SELECT * FROM agent_runs WHERE episode_id IN ({qs}) ORDER BY ts", ids).fetchall()

    open_tasks = []
    from . import checkpoint
    seen = set()
    for e in reversed(eps):
        if e["session_id"] in seen:
            continue
        seen.add(e["session_id"])
        cp = checkpoint.latest(e["session_id"])
        if cp:
            for t in cp.get("open_tasks", []):
                if t["subject"] not in [o["subject"] for o in open_tasks]:
                    open_tasks.append(t)

    L = [f"# {name} — work log, {since} to {until}", ""]
    L.append(f"{len(eps)} working sessions across {len(by_day)} days. "
             f"{sum(e['n_prompts'] for e in eps)} instructions given, "
             f"{len(files)} files changed"
             + (f", {len(runs)} research agents run" if runs else "") + ".")
    L.append("")
    L.append("## What happened, day by day")
    for day, des in by_day.items():
        d = datetime.date.fromisoformat(day)
        L.append(f"\n### {d.strftime('%A %-d %B')}")
        for e in des:
            nf = len(json.loads(e["files_touched"] or "[]"))
            bits = [f"{e['n_prompts']} instructions"]
            if nf:
                bits.append(f"{nf} file{'s' if nf != 1 else ''}")
            if e["n_agents"]:
                bits.append(f"{e['n_agents']} agents")
            L.append(f"- **{_clean(e['title'])}**  \n  <sub>{' · '.join(bits)} · `#{e['id']}`</sub>")
            for m in con.execute("SELECT text FROM messages WHERE episode_id=? AND kind='prompt' "
                                 "ORDER BY ts LIMIT 4", (e["id"],)):
                t = _clean(m["text"] or "")
                if len(t) > 24:
                    L.append(f"  - {t[:220]}")
    if roots:
        L.append("\n## Where the changes landed")
        for r, c in roots.most_common(10):
            L.append(f"- `{r}` — {c} file{'s' if c != 1 else ''}")
    if runs:
        L.append("\n## Research produced")
        for r in runs[:12]:
            head = (r["prompt"] or "").strip().splitlines()
            L.append(f"- {_clean(head[0])[:160] if head else '(no prompt)'} "
                     f"<sub>`chronicle agent {r['id']}`</sub>")
    if open_tasks:
        L.append("\n## Still open")
        for t in open_tasks[:12]:
            L.append(f"- [ ] **{t['subject']}** — {_clean(t.get('description',''))[:200]}")
    L.append("\n---")
    L.append("<sub>Generated by Chronicle from the session record. Every `#id` can be opened with "
             "`chronicle show <id>` for the full detail.</sub>")
    return "\n".join(L)
